package com.sence.net;

/**
 * 网络请求Code识别
 */
public enum HttpCode {
    GET_SYSTEM_TIME,//获取系统消息
    SEARCH_RECOMMEND,//搜索推荐数据
    BIND_CLIENT_ID,//绑定ClientId
    IS_REGISTER,//是否注册
    ADDRESS_ADD,//添加地址
    ADDRESS_EDIT,//编辑地址
    ORDER_LIST,//订单列表
    ADDRESS_LIST,//地址列表
    ADDRESS_DELETE,//删除地址
    GOOD_DETAIL,//商品详情
    SEND_VERIFY_CODE,//发送验证码
    CHECK_VERIFY_CODE,//校验验证码
    REGISTER,//注册
    MAIN_FOCUS,//首页关注
    MAIN_NOTE,//首頁筆記
    MAIN_RECOMMEND,//首页推荐
    VIP_MEMBER,//会员
    KIND_GOODS,//分类
    MESSAGE_INFORM,//通知列表
    SYSTEM_MESSAGE,//系统消息列表
    MESSAGE_CENTRE,//消息中心
    GET_INTRODUCER,//通过邀请码绑定介绍人
    GET_UPNAME,//通过邀请码获得用户名字
    BLACK_LIST,//拉黑列表
    RACHEL,//拉黑
    REPORT,//举报
    SHARE_ADD_WATER,//拉分享商品后增加用户浇水次数
    KIND_GOODS_LIST,//分类下商品列表
    MESSAGE_LIST,//消息中心 - 评论、点赞列表
    BUS_GOODS,//购物车
    USER_DETAIL,//账户明细
    USER_INFO,//我的
    BUS_ADD,//加入购物车
    BUS_RECOMMEND,//购物车推荐
    USER_VIP,//Sence会员
    USER_LOGIN,//用户登录
    SERVE_DETAIL,//服务详情
    COMMENT_SHOP_LIST,//商品评论列表
    SERVE_COMMENT_LIST,//服务评论列表
    ORDER_DETAIL,//订单详情
    CONFIRM_TAKE_GOOD,//确认收货
    DELETE_DONE_ORDER,//删除已完成订单
    TIME_REMAINING,//订单剩余时间
    ORDER_DELETE,//取消待付款，待支付订单
    USER_ENJOY_VIP,//尊享会员
    ORDER_COMMENT_SUPPORT,//评论点赞
    USER_FOCUS_CANCEL,//取消关注
    USER_AUTH,//实名认证
    USER_MYINFO,//我的信息
    USER_INFO_DATA,//我的信息内容
    USER_INFO_DATA_SERVICE,//我的信息服务
    USER_FANS_LIST,//我的粉丝列表
    MAIN_SEARCH,//首页搜索
    USER_FOCUS_LIST,//我的关注列表
    USER_NOTE_LIST,//我的笔记列表
    USER_ACCOUNT,//我的账户
    NOTE_DETAIL,//笔记详情
    NOTE_DELETE,//删除笔记
    CONTENT_DETAIL,//內容詳情
    COMMENT_LIST,//评价列表
    SUPPORT_NOTE_RECOMMEND,//推荐 笔记点赞
    USER_FOCUS,//关注
    BANK_CARD,//我的银行卡列表
    BANK_LIST,//銀行卡列表
    BANK_ADD,//添加银行卡
    SERVICE_ADD_COMMENT,//添加服务评价
    USER_CASH,//提现
    ORDER_COMMIT,//提交订单
    COMMENT_ADD,//添加评论（订单）
    USER_EDIT,//用戶信息修改
    DEFAULT_ADDRESS,//用户默认地址
    USER_GOOD_LIST,//会员商品列表
    USER_SERVE_LIST,//会员vip服务列表
    CHAT_SEND_MESSAGE,//发送消息
    CHAT_CREATE_GROUP,//创建V群
    CHAT_JOIN,//加入V群
    PRIVATE_CHAT_LIST,//私聊列表
    CHAT_MEMBER_LIST,//V群成員列表
    CHAT_ENTER,//進入V群
    CHAT_GROUP_LIST,//V群列表
    CHAT_READ_GROUP,//消息已读
    CHAT_PRIVATE_LIST,//私聊记录列表
    CHAT_PRIVATE_READ,//私聊已读
    CHAT_PRIVATE_SEND,//私聊发送消息
    COMMENT_DETAIL_ADD,//添加评论
    COMMENT_SUPPORT,//评论点赞
    NOTE_ADD,//添加笔记
    PAY_ALI,//支付宝支付
    PAY_WX,//微信支付
    MY_PRIVATE_LIST,//我的私聊列表
    MY_SUPPORT,//我的赞
    MY_COMMENT,//我的评论
    VIP_OPEN,//开通会员
    START_PICTURE,//驱动图片
    UPDATE_APP,//更新版本
    CHAT_BAN,//禁言
}
